title: CARPE DIEM
theme: jekyll-theme-minimal
paginate: 8
url: id0o0bi.github.com
plugins: [jekyll-paginate]
feed: no
author: id0o0bi
follow: id0o0bi
indexContent: true
blogName: id0o0bi
copyright: 2017-2020